### ISSUE TITLE
Visual and algorithmic event detection 

### ISSUE THREAD

**Issue by eren-ck** [eren-ck/collective-movement-exploration#34]
# Visual and algorithmic event detection 

Detect, score and visualize event - when multiple parameters exceed a given theshold 

- [ ] Define what a task is
- [ ] Which parameters are important 
- [ ] How and who defines the thresholds

**Comment by thejordanlab** [comment]
Hey Eren,
    From our side, this will approached in two ways. Short term is from traditional ethograms using annotated approaches. Students will score each behavior by hand, and examine the coincident parameter values for those events. Second, longer term goal is to use unsupervised methods to cluster events.
